### ISSUE TITLE
Windows tests failing in CI

### ISSUE THREAD

**Issue by vijayfractl** [fractl-io/fractl#1214]
Error:

```
Run git clone https://***@github.com/fractl-io/fractl-config-secrets-reader
Cloning into 'fractl-config-secrets-reader'...
Error: Could not find or load main class "-Dclojure.compile.path=D:\a\fractl\fractl\fractl-config-secrets-reader.target.classes"
Caused by: java.lang.ClassNotFoundException: "-Dclojure.compile.path=D:\a\fractl\fractl\fractl-config-secrets-reader.target.classes"
Error: Process completed with exit code 1.
```

**Comment by pratik-fractl** [comment]
After contacting Github support with this email:

> Hi,
>
> We have a repository called [Fractl](https://github.com/fractl-io/fractl) where we have bunch of actions
> like test-clj which runs on ubuntu-latest and windows-latest.
>
> The problem now is, the same Action which was running without any change on codebases, is working
> for ubuntu-latest but, failing for windows-latest. We do, have some community based Marketplace
> actions for support of Clojure and Leiningen, but, upon our debugging we tested that, bumping the versions
> of the community actions, Java action/version wasn't the culprit.
>
> The issue can be seen [here](https://github.com/fractl-io/fractl/actions/runs/7796190195/job/21260395352?pr=1221).
>
> Please, provide us with the knowledge of what is happening with the Action build on Windows and also, guidance
> on how to fix it.
>
> Thanks.


Received this reply:

Hi Pratik,
 
Thank you for contacting us! We appreciate your interest in GitHub.
 
We offer support to our users based on certain categories, as explained in our documentation: [About GitHub Support](https://docs.github.com/en/support/learning-about-github-support/about-github-support#about-github-support). In this case, your question is better suited for the maintainers over at: https://github.com/actions/runner-images/issues.
 
It looks like the Windows image has updated since the last successful run:
https://github.com/fractl-io/fractl/actions/runs/7690993525/job/20955621629#step:1:9 
 
https://github.com/fractl-io/fractl/actions/runs/7796190195/job/21260395352#step:1:9
 
This was the version update:
https://github.com/actions/runner-images/pull/9294
 
I'd recommend reaching out and sharing any relevant examples for the team to investigate further.
 
I hope this helps! Please let us know if you have any questions, or if we can help with anything else at the moment.
 
Cheers,
James

**Comment by pratik-fractl** [comment]
Opened an issue here: https://github.com/actions/runner-images/issues/9315
